baseURL = "http://www.coredigger.io/"
languageCode = "ko-kr"
title = "Core Digger"
theme = "hugo-theme-learn"
[params]
    themeVariant = "mine"
    editURL = "https://github.com/Hsqb/coredigger-site/blob/master/content/"
    home = [ "HTML", "RSS", "JSON"]